import json
from pathlib import Path

import torch
from torch.utils.data import Dataset


class ShardedDataset(Dataset):
    """
    Loads JSONL shards generated by generate_data.py
    """

    def __init__(self, data_dir: str):
        self.records = []

        data_path = Path(data_dir)

        shard_files = sorted(data_path.glob("shard_*.jsonl"))

        if not shard_files:
            raise ValueError(
                f"No shard files found in {data_dir}"
            )

        for shard_file in shard_files:
            with shard_file.open("r", encoding="utf-8") as f:
                for line in f:
                    self.records.append(json.loads(line))

        print(
            f"Loaded {len(self.records)} records "
            f"from {len(shard_files)} shards"
        )

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        row = self.records[idx]

        tokens = torch.tensor(
            row["tokens"],
            dtype=torch.long
        )

        label = torch.tensor(
            row["label"],
            dtype=torch.long
        )

        return tokens, label